### PR TITLE
benchmark with timeit

### PR DESCRIPTION
**Pull request by ameligrana**

### CODE REVIEW

**Comment by ameligrana** [comment]
the two pr are linked because of the support of torus, implictly assumed here

**Comment by ameligrana** [comment]
Anyway I'm trying to rewrite your code with the new syntax cython + mypy :-)

edit: still in alpha, so let's stick with the older way

**Comment by rht** [comment]
I want to merge this one because `timeit` is more accurate.

**Comment by rht** [comment]
Is there a way around having to specify the setup and statement as a string? Sometimes the setup is multiline, and not having syntax highlighting and any syntax-aware `$EDITOR` feature is not ideal.

**Comment by Tortar** [comment]
I think one workaround would be putting the statements in another file and then import them as a text file

**Comment by ameligrana** [comment]
mmh, let me search a bit and see if there is a solution

**Comment by ameligrana** [comment]
yes, to me having all of setup and stmt in sequence with a separator in another file to parse as a text file seems the best solution

**Comment by ameligrana** [comment]
will rewrite it soon this way :-)

**Comment by rht** [comment]
Nah, it's simpler with a string for now then.

**Pull request closed without merging**
