### PR TITLE
finish get_neighborhood in cython_grid

### PR DESCRIPTION
**Pull request by ameligrana**

### CODE REVIEW

**Comment by ameligrana** [comment]
I saw your latest commit, I think we should instead create a conversion method which converts to list and leave the get_neighborhood return the ndarray

**Comment by rht** [comment]
Yeah, I was just adding that code as a note. We haven't decided on whether to go with Numba or Cython yet, I think we should delay the actual implementation until then.

**Comment by ameligrana** [comment]
yeah indeed I was thinking that you are doing it for this reason

**Comment by ameligrana** [comment]
Does the conversion cost the same in the two frameworks?

**Comment by rht** [comment]
Yes, the elapsed is similar.

**Comment by ameligrana** [comment]
implemented inside mesa_perf folder

**Pull request closed without merging**
